# Generated by Django 4.2.4 on 2023-08-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCommentFromTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comment', to='authentication.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_comment', to='authentication.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_comment', to='authentication.teacher')),
            ],
            options={
                'verbose_name': 'Student Comment From Teacher',
                'verbose_name_plural': 'Student Comments From Teachers',
                'ordering': ['-id'],
            },
        ),
    ]
