# Generated by Django 4.2.4 on 2023-08-28 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReplyToTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='comment.studentcommentfromteacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reply', to='authentication.student')),
            ],
            options={
                'verbose_name': 'Comment Reply To Teacher',
                'verbose_name_plural': 'Comment Replies To Teachers',
                'ordering': ['-id'],
            },
        ),
    ]
