# Generated by Django 4.2.4 on 2023-08-28 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('comment', '0002_commentreplytoteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReplyToTeacherFromParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply_from_parent', to='comment.studentcommentfromteacher')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_reply', to='authentication.parent')),
            ],
            options={
                'verbose_name': 'Comment Reply To Teacher From Parent',
                'verbose_name_plural': 'Comment Replies To Teachers From Parents',
                'ordering': ['-id'],
            },
        ),
    ]
