# Generated by Django 4.2.4 on 2023-09-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_commentreplytoteacherfromparent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReplyToTeacher',
        ),
    ]
