# Generated by Django 4.2.4 on 2023-09-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='days',
            field=models.CharField(choices=[('Mon, Wed, Fri', 'Mon, Wed, Fri'), ('Tue, Thu, Sat', 'Tue, Thu, Sat')], default='Mon, Wed, Fri', max_length=150, null=True),
        ),
    ]
