# Generated by Django 4.2.4 on 2023-09-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_group_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='slug',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
    ]
